### ISSUE TITLE
About mi_f_score(close_pred, close_labels, open_pred, open_labels, ts):

### ISSUE THREAD

**Issue by 447162527** [wang22ti/OpenAUC#3]
English:
Good hight, I hope it would not bother you that, I had run your code on <MNIST/CIFAR10/SVHN> Dataset, and it seems good running. However，when I ran the code on <tinyimagenet(on which I had run 'create_val_img_folder')/cifar-10-100-10/cifar-10-100-50>. There were some errors on mi_f_score:

Traceback (most recent call last):
  File "osr.py", line 307, in <module>
    main_worker(options, args)
  File "osr.py", line 201, in main_worker
    results = test(net, testloader, outloader, **options)
  File "osr.py", line 120, in test
    results = evaluate.evaluate(evaluate, load=False, preds=preds, normalised_ap=False)
  File "/home/zjhuang/A2022/OpenAUC/utils/test_utils.py", line 397, in evaluate
    mi = mi_f_score(closed_set_preds, closed_set_labels, open_set_preds, open_set_labels, ts)
  File "/home/zjhuang/A2022/OpenAUC/utils/test_utils.py", line 37, in mi_f_score
    tp[cl] += 1 if c_pred == cl and o_pred == 0 and ol == 0 else 0
IndexError: list index out of range

I didn't know why this would happen on these three dataset and not happen on <MNIST/CIFAR10/SVHN> because I didn't change the code mostly. It would be better if you could give me some advice.

中文：
作者先生您好，冒昧打扰您关于代码的一些问题，我在运行您的代码，试图复现您的结果的过程中，在<MNIST/CIFAR10/SVHN>上能够正常运行(只更改'dataset'这一项)，而在<tinyimagenet(已提前运行 'create_val_img_folder')/cifar-10-100-10/cifar-10-100-50>上却会报这个错，不知道是什么原因，因为我只更改了'--dataset'和‘out-num’两项，如有打扰，请多海涵。

**Comment by wang22ti** [comment]
建议你输出一下这些数据集上 close_pred 的 shape

**Comment by 447162527** [comment]
谢谢您的回复，我发现了问题：
以'TinyImageNet'的第0个闭集训练集设置为例：
[108, 147, 17, 58, 193, 123, 72, 144, 75, 167, 134, 14, 81, 171, 44, 197, 152, 66, 1, 133]这些是真实数字，
然而close_labels和open_labels中仍然显示这些数字，而不是[0,1,...,19],那么
由于ma_f_score中的tp是一个整型数字，不存在索引的问题，故不报错；
而mi_f_score中的tp是一个{list:20}列表，故会出现

for c_pred, o_pred, cl, ol in zip(close_pred_, open_pred_, close_labels, open_labels):       中的cl为一个大于19的数：
tp[cl] +=1    -->                 tp[some number >19]           --> list index out of range,
因为tp[cl] += 1这个索引值cl不能超过19,但是cl由来自于close_labels里，我还在想如何debug，如果有指点，不胜感激

举例有误，因为是在测试集上测试，标签可能不是[108, 147, 17, 58, 193, 123, 72, 144, 75, 167, 134, 14, 81, 171, 44, 197, 152, 66, 1, 133]，而是[18,3,5,17,12,...,178,179]
